import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Predictable constraint names so future Alembic migrations that touch a
# single constraint (add_column + FK, etc.) always have a name to target —
# without this, autogenerate emits `create_foreign_key(None, ...)` and the
# matching downgrade has no name to drop.
_NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    metadata = MetaData(naming_convention=_NAMING_CONVENTION)


class PrimaryKeyMixin:
    """UUID primary key, generated by Postgres."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )


class TimestampMixin:
    """created_at / updated_at for mutable rows."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class CreatedAtMixin:
    """created_at only, for append-only / immutable rows."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class BitemporalMixin:
    """valid_from / valid_to / recorded_at for regulatory and profile tables.

    valid_from/valid_to describe the real-world period the row's content is
    correct for (business time); recorded_at is when Provision learned it
    (system time). A row is never edited in place to reflect a change — a
    new row is recorded and the old one's valid_to is closed.
    """

    valid_from: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    valid_to: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    recorded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class TenantScopedMixin:
    """Mixin for tables holding tenant data.

    CONVENTIONS.md rule #3: no database query without tenant scoping.
    Every table holding tenant data carries tenant_id directly (even where
    it is also reachable via a workspace_id join), so every query can and
    must filter on it without a join — see db/session.py::tenant_session.
    """

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id"), index=True, nullable=False
    )
