"""initial schema

Revision ID: 286f163a5509
Revises: 
Create Date: 2026-07-10 23:30:15.223188

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '286f163a5509'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('citation', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_table('instrument_versions',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_versions_instrument_id'), 'instrument_versions', ['instrument_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('codename', sa.String(), nullable=False),
    sa.Column('real_name', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codename', name='uq_workspace_tenant_codename')
    )
    op.create_index(op.f('ix_workspaces_tenant_id'), 'workspaces', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_table('clauses',
    sa.Column('instrument_version_id', sa.UUID(), nullable=False),
    sa.Column('clause_ref', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_version_id'], ['instrument_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clauses_instrument_version_id'), 'clauses', ['instrument_version_id'], unique=False)
    op.create_table('entity_profiles',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('companies_house_number', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'version', name='uq_entity_profile_workspace_version')
    )
    op.create_index(op.f('ix_entity_profiles_tenant_id'), 'entity_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_entity_profiles_workspace_id'), 'entity_profiles', ['workspace_id'], unique=False)
    op.create_table('error_register',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_register_tenant_id'), 'error_register', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_error_register_workspace_id'), 'error_register', ['workspace_id'], unique=False)
    op.create_table('memberships',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('invited_email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ANALYST', 'APPROVER', 'VIEWER', name='role'), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'REVOKED', name='membership_status'), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'invited_email', name='uq_membership_workspace_invitee')
    )
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_memberships_workspace_id'), 'memberships', ['workspace_id'], unique=False)
    op.create_table('metrics_events',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_events_tenant_id'), 'metrics_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_metrics_events_workspace_id'), 'metrics_events', ['workspace_id'], unique=False)
    op.create_table('sweep_runs',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETE', 'FAILED', name='sweep_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sweep_runs_tenant_id'), 'sweep_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sweep_runs_workspace_id'), 'sweep_runs', ['workspace_id'], unique=False)
    op.create_table('analyses',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('entity_profile_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETE', 'FAILED', name='analysis_status'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_profile_id'], ['entity_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_entity_profile_id'), 'analyses', ['entity_profile_id'], unique=False)
    op.create_index(op.f('ix_analyses_tenant_id'), 'analyses', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_analyses_workspace_id'), 'analyses', ['workspace_id'], unique=False)
    op.create_table('obligations',
    sa.Column('clause_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('obligation_type', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_clause_id'), 'obligations', ['clause_id'], unique=False)
    op.create_table('profile_fields',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('entity_profile_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('field_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.Enum('REGISTRY', 'FILING', 'USER', 'DEFAULT', 'ESTIMATE', 'UNKNOWN', name='profile_field_source'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_profile_id'], ['entity_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_profile_id', 'field_key', name='uq_profile_field_version_key')
    )
    op.create_index(op.f('ix_profile_fields_entity_profile_id'), 'profile_fields', ['entity_profile_id'], unique=False)
    op.create_index(op.f('ix_profile_fields_tenant_id'), 'profile_fields', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_profile_fields_workspace_id'), 'profile_fields', ['workspace_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('entity_profile_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', name='source_document_status'), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['entity_profile_id'], ['entity_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_tenant_id'), 'source_documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_source_documents_workspace_id'), 'source_documents', ['workspace_id'], unique=False)
    op.create_table('cost_templates',
    sa.Column('obligation_id', sa.UUID(), nullable=True),
    sa.Column('formula', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_templates_obligation_id'), 'cost_templates', ['obligation_id'], unique=False)
    op.create_table('memos',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memos_tenant_id'), 'memos', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memos_workspace_id'), 'memos', ['workspace_id'], unique=False)
    op.create_table('predicates',
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('predicate_key', sa.String(), nullable=False),
    sa.Column('expression', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predicates_obligation_id'), 'predicates', ['obligation_id'], unique=False)
    op.create_table('analysis_items',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('predicate_id', sa.UUID(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['predicate_id'], ['predicates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_items_analysis_id'), 'analysis_items', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_items_tenant_id'), 'analysis_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_analysis_items_workspace_id'), 'analysis_items', ['workspace_id'], unique=False)
    op.create_table('forecast_log',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('predicate_id', sa.UUID(), nullable=True),
    sa.Column('forecast_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['predicate_id'], ['predicates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_log_tenant_id'), 'forecast_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_forecast_log_workspace_id'), 'forecast_log', ['workspace_id'], unique=False)
    op.create_table('memo_versions',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('memo_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', name='memo_status'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['memo_id'], ['memos.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memo_versions_memo_id'), 'memo_versions', ['memo_id'], unique=False)
    op.create_index(op.f('ix_memo_versions_tenant_id'), 'memo_versions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memo_versions_workspace_id'), 'memo_versions', ['workspace_id'], unique=False)
    op.create_table('assumptions',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('memo_version_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memo_version_id'], ['memo_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assumptions_memo_version_id'), 'assumptions', ['memo_version_id'], unique=False)
    op.create_index(op.f('ix_assumptions_tenant_id'), 'assumptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_assumptions_workspace_id'), 'assumptions', ['workspace_id'], unique=False)
    op.create_table('reports',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('memo_version_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['memo_version_id'], ['memo_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_tenant_id'), 'reports', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_reports_workspace_id'), 'reports', ['workspace_id'], unique=False)
    op.create_table('reviews',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('memo_version_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'CHANGES_REQUESTED', 'REJECTED', name='review_decision'), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memo_version_id'], ['memo_versions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_memo_version_id'), 'reviews', ['memo_version_id'], unique=False)
    op.create_index(op.f('ix_reviews_tenant_id'), 'reviews', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_reviews_workspace_id'), 'reviews', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_workspace_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_tenant_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_memo_version_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_reports_workspace_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_tenant_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_assumptions_workspace_id'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_tenant_id'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_memo_version_id'), table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_index(op.f('ix_memo_versions_workspace_id'), table_name='memo_versions')
    op.drop_index(op.f('ix_memo_versions_tenant_id'), table_name='memo_versions')
    op.drop_index(op.f('ix_memo_versions_memo_id'), table_name='memo_versions')
    op.drop_table('memo_versions')
    op.drop_index(op.f('ix_forecast_log_workspace_id'), table_name='forecast_log')
    op.drop_index(op.f('ix_forecast_log_tenant_id'), table_name='forecast_log')
    op.drop_table('forecast_log')
    op.drop_index(op.f('ix_analysis_items_workspace_id'), table_name='analysis_items')
    op.drop_index(op.f('ix_analysis_items_tenant_id'), table_name='analysis_items')
    op.drop_index(op.f('ix_analysis_items_analysis_id'), table_name='analysis_items')
    op.drop_table('analysis_items')
    op.drop_index(op.f('ix_predicates_obligation_id'), table_name='predicates')
    op.drop_table('predicates')
    op.drop_index(op.f('ix_memos_workspace_id'), table_name='memos')
    op.drop_index(op.f('ix_memos_tenant_id'), table_name='memos')
    op.drop_table('memos')
    op.drop_index(op.f('ix_cost_templates_obligation_id'), table_name='cost_templates')
    op.drop_table('cost_templates')
    op.drop_index(op.f('ix_source_documents_workspace_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_tenant_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_profile_fields_workspace_id'), table_name='profile_fields')
    op.drop_index(op.f('ix_profile_fields_tenant_id'), table_name='profile_fields')
    op.drop_index(op.f('ix_profile_fields_entity_profile_id'), table_name='profile_fields')
    op.drop_table('profile_fields')
    op.drop_index(op.f('ix_obligations_clause_id'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_analyses_workspace_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_tenant_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_entity_profile_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_sweep_runs_workspace_id'), table_name='sweep_runs')
    op.drop_index(op.f('ix_sweep_runs_tenant_id'), table_name='sweep_runs')
    op.drop_table('sweep_runs')
    op.drop_index(op.f('ix_metrics_events_workspace_id'), table_name='metrics_events')
    op.drop_index(op.f('ix_metrics_events_tenant_id'), table_name='metrics_events')
    op.drop_table('metrics_events')
    op.drop_index(op.f('ix_memberships_workspace_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_error_register_workspace_id'), table_name='error_register')
    op.drop_index(op.f('ix_error_register_tenant_id'), table_name='error_register')
    op.drop_table('error_register')
    op.drop_index(op.f('ix_entity_profiles_workspace_id'), table_name='entity_profiles')
    op.drop_index(op.f('ix_entity_profiles_tenant_id'), table_name='entity_profiles')
    op.drop_table('entity_profiles')
    op.drop_index(op.f('ix_clauses_instrument_version_id'), table_name='clauses')
    op.drop_table('clauses')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_workspaces_tenant_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_instrument_versions_instrument_id'), table_name='instrument_versions')
    op.drop_table('instrument_versions')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('instruments')
    # ### end Alembic commands ###

    # Alembic's autogenerate doesn't emit DROP TYPE for Postgres enums it
    # implicitly created via Enum columns — drop them explicitly so a
    # downgrade followed by a re-upgrade doesn't hit "type already exists".
    for enum_name in (
        "role",
        "membership_status",
        "profile_field_source",
        "analysis_status",
        "memo_status",
        "review_decision",
        "source_document_status",
        "sweep_run_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
