"""tenant created_by_user_id

Revision ID: 2b7f48ee11c9
Revises: ebff3e065651
Create Date: 2026-07-10 23:38:59.346881

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '2b7f48ee11c9'
down_revision: str | None = 'ebff3e065651'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('created_by_user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(
        'fk_tenants_created_by_user_id_users', 'tenants', 'users', ['created_by_user_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tenants_created_by_user_id_users', 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'created_by_user_id')
    # ### end Alembic commands ###
