"""review workflow, error register, memo staleness schema

Revision ID: 688c6b4d633a
Revises: a3f1c9d47b2e
Create Date: 2026-07-12 15:11:31.340064

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '688c6b4d633a'
down_revision: str | None = 'a3f1c9d47b2e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memo_input_change_flags',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('memo_version_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('instrument_version_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_memo_input_change_flags_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['instrument_version_id'], ['instrument_versions.id'], name=op.f('fk_memo_input_change_flags_instrument_version_id_instrument_versions')),
    sa.ForeignKeyConstraint(['memo_version_id'], ['memo_versions.id'], name=op.f('fk_memo_input_change_flags_memo_version_id_memo_versions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_memo_input_change_flags_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_memo_input_change_flags_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memo_input_change_flags'))
    )
    op.create_index(op.f('ix_memo_input_change_flags_memo_version_id'), 'memo_input_change_flags', ['memo_version_id'], unique=False)
    op.create_index(op.f('ix_memo_input_change_flags_tenant_id'), 'memo_input_change_flags', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memo_input_change_flags_workspace_id'), 'memo_input_change_flags', ['workspace_id'], unique=False)
    op.create_table('review_corrections',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('memo_version_id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=True),
    sa.Column('cost_template_id', sa.UUID(), nullable=True),
    sa.Column('corrected_by_user_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by_user_id'], ['users.id'], name=op.f('fk_review_corrections_corrected_by_user_id_users')),
    sa.ForeignKeyConstraint(['cost_template_id'], ['cost_templates.id'], name=op.f('fk_review_corrections_cost_template_id_cost_templates')),
    sa.ForeignKeyConstraint(['memo_version_id'], ['memo_versions.id'], name=op.f('fk_review_corrections_memo_version_id_memo_versions')),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('fk_review_corrections_obligation_id_obligations')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_review_corrections_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_review_corrections_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_corrections'))
    )
    op.create_index(op.f('ix_review_corrections_memo_version_id'), 'review_corrections', ['memo_version_id'], unique=False)
    op.create_index(op.f('ix_review_corrections_tenant_id'), 'review_corrections', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_review_corrections_workspace_id'), 'review_corrections', ['workspace_id'], unique=False)
    op.add_column('error_register', sa.Column('root_cause', sa.String(), nullable=True))
    op.add_column('error_register', sa.Column('affected_workspace_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('error_register', sa.Column('disclosure_note', sa.String(), nullable=True))
    op.add_column('error_register', sa.Column('disclosure_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('memo_versions', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('memos', sa.Column('used_in_ic', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('panel_firm', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'panel_firm')
    op.drop_column('memos', 'used_in_ic')
    op.drop_column('memo_versions', 'submitted_at')
    op.drop_column('error_register', 'disclosure_sent_at')
    op.drop_column('error_register', 'disclosure_note')
    op.drop_column('error_register', 'affected_workspace_ids')
    op.drop_column('error_register', 'root_cause')
    op.drop_index(op.f('ix_review_corrections_workspace_id'), table_name='review_corrections')
    op.drop_index(op.f('ix_review_corrections_tenant_id'), table_name='review_corrections')
    op.drop_index(op.f('ix_review_corrections_memo_version_id'), table_name='review_corrections')
    op.drop_table('review_corrections')
    op.drop_index(op.f('ix_memo_input_change_flags_workspace_id'), table_name='memo_input_change_flags')
    op.drop_index(op.f('ix_memo_input_change_flags_tenant_id'), table_name='memo_input_change_flags')
    op.drop_index(op.f('ix_memo_input_change_flags_memo_version_id'), table_name='memo_input_change_flags')
    op.drop_table('memo_input_change_flags')
    # ### end Alembic commands ###
