"""instrument onboarding and applicability schema

Revision ID: b8fc7df2da0c
Revises: ed60d093520a
Create Date: 2026-07-11 20:20:02.096478

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b8fc7df2da0c'
down_revision: str | None = 'ed60d093520a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # add_column (unlike create_table) doesn't implicitly CREATE TYPE for
    # a new Postgres enum, so both are created explicitly before use.
    postgresql.ENUM("BINDS", "DOES_NOT_BIND", "AMBIGUOUS", name="analysis_item_outcome").create(
        op.get_bind(), checkfirst=True
    )
    postgresql.ENUM("DRAFT", "APPROVED", name="predicate_status").create(
        op.get_bind(), checkfirst=True
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_items', sa.Column('outcome', sa.Enum('BINDS', 'DOES_NOT_BIND', 'AMBIGUOUS', name='analysis_item_outcome'), nullable=False))
    op.add_column('analysis_items', sa.Column('missing_field_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('analysis_items', sa.Column('rationale', sa.String(), nullable=False))
    op.drop_column('analysis_items', 'matched')
    op.add_column('clauses', sa.Column('ordinal', sa.Integer(), nullable=False))
    op.add_column('cost_templates', sa.Column('name', sa.String(), nullable=False))
    op.add_column('cost_templates', sa.Column('drivers', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('cost_templates', sa.Column('source_basis', sa.String(), nullable=False))
    op.add_column('cost_templates', sa.Column('maturity_tier', sa.String(), nullable=False))
    op.add_column('instrument_versions', sa.Column('content_hash', sa.String(), nullable=False))
    op.add_column('instrument_versions', sa.Column('raw_text', sa.String(), nullable=False))
    op.create_index(op.f('ix_instrument_versions_content_hash'), 'instrument_versions', ['content_hash'], unique=False)
    op.add_column('obligations', sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('obligations', sa.Column('confidence', sa.Integer(), nullable=False))
    op.add_column('obligations', sa.Column('extracted_by', sa.String(), nullable=False))
    op.add_column('obligations', sa.Column('approved', sa.Boolean(), nullable=False))
    op.add_column('obligations', sa.Column('approved_by_user_id', sa.UUID(), nullable=True))
    op.add_column('obligations', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_obligations_approved_by_user_id_users'), 'obligations', 'users', ['approved_by_user_id'], ['id'])
    op.add_column('predicates', sa.Column('status', sa.Enum('DRAFT', 'APPROVED', name='predicate_status'), nullable=False))
    op.add_column('predicates', sa.Column('drafted_by_ai', sa.Boolean(), nullable=False))
    op.add_column('predicates', sa.Column('approved_by_user_id', sa.UUID(), nullable=True))
    op.add_column('predicates', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_predicates_approved_by_user_id_users'), 'predicates', 'users', ['approved_by_user_id'], ['id'])
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    op.drop_constraint(op.f('fk_predicates_approved_by_user_id_users'), 'predicates', type_='foreignkey')
    op.drop_column('predicates', 'approved_at')
    op.drop_column('predicates', 'approved_by_user_id')
    op.drop_column('predicates', 'drafted_by_ai')
    op.drop_column('predicates', 'status')
    op.drop_constraint(op.f('fk_obligations_approved_by_user_id_users'), 'obligations', type_='foreignkey')
    op.drop_column('obligations', 'approved_at')
    op.drop_column('obligations', 'approved_by_user_id')
    op.drop_column('obligations', 'approved')
    op.drop_column('obligations', 'extracted_by')
    op.drop_column('obligations', 'confidence')
    op.drop_column('obligations', 'fields')
    op.drop_index(op.f('ix_instrument_versions_content_hash'), table_name='instrument_versions')
    op.drop_column('instrument_versions', 'raw_text')
    op.drop_column('instrument_versions', 'content_hash')
    op.drop_column('cost_templates', 'maturity_tier')
    op.drop_column('cost_templates', 'source_basis')
    op.drop_column('cost_templates', 'drivers')
    op.drop_column('cost_templates', 'name')
    op.drop_column('clauses', 'ordinal')
    op.add_column('analysis_items', sa.Column('matched', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('analysis_items', 'rationale')
    op.drop_column('analysis_items', 'missing_field_keys')
    op.drop_column('analysis_items', 'outcome')
    # ### end Alembic commands ###

    # Autogenerate doesn't emit DROP TYPE for the enums it implicitly
    # created — see the same note in 286f163a5509_initial_schema.py.
    for enum_name in ("analysis_item_outcome", "predicate_status"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
