"""impact engine range phasing pv confidence grade schema

Revision ID: f482eaa41929
Revises: 8773e87dd92a
Create Date: 2026-07-12 13:56:26.546110

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f482eaa41929'
down_revision: str | None = '8773e87dd92a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('discount_rate_pct', sa.Numeric(precision=6, scale=3), nullable=False))
    op.add_column('analyses', sa.Column('fx_rate', sa.Numeric(precision=12, scale=6), nullable=False))
    op.add_column('analyses', sa.Column('base_currency', sa.String(), nullable=False))
    op.add_column('analysis_items', sa.Column('impact_low', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('analysis_items', sa.Column('impact_high', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('analysis_items', sa.Column('present_value', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('analysis_items', sa.Column('phased_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('assumptions', sa.Column('source', sa.String(), nullable=False))
    op.add_column('cost_templates', sa.Column('first_obligation_date', sa.Date(), nullable=True))
    op.add_column('cost_templates', sa.Column('transition_months', sa.Integer(), nullable=False))
    op.add_column('instruments', sa.Column('in_flight', sa.Boolean(), nullable=False))
    op.add_column('memo_versions', sa.Column('confidence_grade', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memo_versions', 'confidence_grade')
    op.drop_column('instruments', 'in_flight')
    op.drop_column('cost_templates', 'transition_months')
    op.drop_column('cost_templates', 'first_obligation_date')
    op.drop_column('assumptions', 'source')
    op.drop_column('analysis_items', 'phased_schedule')
    op.drop_column('analysis_items', 'present_value')
    op.drop_column('analysis_items', 'impact_high')
    op.drop_column('analysis_items', 'impact_low')
    op.drop_column('analyses', 'base_currency')
    op.drop_column('analyses', 'fx_rate')
    op.drop_column('analyses', 'discount_rate_pct')
    # ### end Alembic commands ###
